### ISSUE TITLE
Error  : We're unable to complete your request

### ISSUE THREAD

**Issue by StephenAtty** [shawntabrizi/Microsoft-Authentication-with-MSAL.js#1]
I was just checking your code ( https://www.shawntabrizi.com/aad/building-a-simple-sign-in-page-with-msal-js-for-microsoft-identities/ )  to see if it will give me the functionality I need but it fails when I try to login with the following error when I followed the link to your example page

We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by p0tvin29** [comment]
@StephenAtty In your microsoft azure app registration, make sure the redirect URI is the same URL you are accessing this from.  I had the same problem when I tried to open the index.html file from the folder on my computer.... I had to put it on my web server and made sure redirect URI was the same as my web server.

**Comment by StephenAtty** [comment]
What I was pointing out is that your example of it working on https://www.shawntabrizi.com/Microsoft-Authentication-with-MSAL.js/ actually doesn't
